k8s minifest changes

diff --git a/.github/workflows/prod_deploy.yml b/.github/workflows/prod_deploy.yml
--- a/.github/workflows/prod_deploy.yml
+++ b/.github/workflows/prod_deploy.yml
@@ -62,13 +62,11 @@ jobs:
           kubectl apply -f k8s/ps-service.yaml || { echo 'kubectl posgres service apply failed'; exit 1; }
           
           echo "Applying Kubernetes manifests... hyn app"
-          kubectl apply -f k8s/hyn-app.yaml || { echo 'kubectl apply failed'; exit 1; }
+          kubectl apply -f k8s/django-deployment.yaml || { echo 'kubectl apply failed'; exit 1; }
 
-          echo "Applying Kubernetes manifests.. hyn app service."
-          kubectl apply -f k8s/hyn-app-service.yaml || { echo 'kubectl apply failed hyn app service'; exit 1; }
-
+        
           echo "Checking rollout status..."
-          kubectl rollout status deployment/hyn-deployment || { echo 'Deployment rollout failed'; exit 1; }
+          kubectl rollout status deployment/django-deployment || { echo 'Deployment rollout failed'; exit 1; }
 
           echo "Kubernetes deployment successful!"
           EOF
